name: book
channels:
  - conda-forge
dependencies:
  - jupyter-book=1
  - xeus-octave
  - octave
  - octave-control
  - octave-signal
  - python=3.12
  - jupyterlab
  - ipywidgets
  - fortran-compiler
  - cxx-compiler
  - poppler
  - control
  - jupyterlab-myst
  - pip:
      - ghp-import
      - jupyter-matlab-proxy
      - sphinxemoji
      - jupyter-tikz
      - jb1-zoomies
